'use strict';
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { gzipSync } = require('node:zlib');
const playwright = require('playwright');
const root = path.resolve(__dirname, '../..');
const generated = process.env.FRONTEND_FIXTURES || path.join(__dirname, '.generated');
const artifacts = path.join(__dirname, 'artifacts');
const engines = (process.env.FRONTEND_BROWSERS || 'chromium,firefox').split(',');
const browsers = {};
fs.mkdirSync(artifacts, { recursive: true });
const queue = JSON.parse(fs.readFileSync(path.join(generated, 'queue.json')));

before(async () => {
    for (const engine of engines) browsers[engine] = await playwright[engine].launch({ headless: true });
});
after(async () => { for (const browser of Object.values(browsers)) await browser.close(); });

// Only playback and upstream responses are stubbed. Templates, CSS and UI scripts
// are production code. No request is allowed to escape this fixture origin.
const playerStub = `
window.__ended = []; window.__time = 0;
window.player = {
 on: function(event, cb) { if (event === 'ended') window.__ended.push(cb); },
 off: function(event, cb) { if (event === 'ended') window.__ended = window.__ended.filter(f => f !== cb); },
 currentTime: function(value) { if (value !== undefined) window.__time = value; return window.__time; }
};`;
const picture = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"><defs><linearGradient id="sky" x2="1" y2="1"><stop stop-color="#213b6b"/><stop offset=".6" stop-color="#744287"/><stop offset="1" stop-color="#df9378"/></linearGradient></defs><path fill="url(#sky)" d="M0 0h1280v720H0z"/><circle cx="860" cy="230" r="92" fill="#f4ccaf"/><path d="m0 520 360-330 440 440 250-285 230 235v140H0z" fill="#1e253d"/><path d="m0 655 430-215 470 200 380-160v240H0z" fill="#131b2d"/></svg>`;

async function pageFor(engine, options = {}) {
    const context = await browsers[engine].newContext({
        viewport: { width: options.width || 1440, height: options.height || 1000 },
        javaScriptEnabled: options.javascript !== false,
        colorScheme: options.systemTheme || 'dark',
        reducedMotion: 'reduce',
        hasTouch: Boolean(options.touch),
        ...(options.mobileUserAgent ? { userAgent: 'Mozilla/5.0 (Linux; Android 15; Mobile) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36' } : {})
    });
    const page = await context.newPage();
    const errors = [];
    const requests = [];
    page.on('pageerror', error => errors.push(error.message));
    let queueCalls = 0;
    let transcriptCalls = 0;
    const fixture = options.fixture || 'watch-dark';
    await page.route('**/*', async route => {
        const url = new URL(route.request().url());
        requests.push(url.pathname + url.search);
        if (route.request().isNavigationRequest()) {
            return route.fulfill({ contentType: 'text/html', body: fs.readFileSync(path.join(generated, fixture + '.html'), 'utf8') });
        }
        if (url.pathname.startsWith('/api/v1/dearrow/')) {
            if (options.dearrowError) return route.fulfill({ status: 503, body: '{}' });
            return route.fulfill({ contentType: 'application/json', body: JSON.stringify({title: options.dearrowMissing ? null : 'A clear title <img src=x onerror=alert(1)>'}) });
        }
        if (url.pathname === '/api/v1/auth/subscriptions') return route.fulfill({ contentType: 'application/json', body: '[]' });
        if (url.pathname === '/api/v1/auth/notifications') return route.fulfill({ contentType: 'text/event-stream', body: ': fixture\n\n' });
        if (/^\/api\/v1\/(playlists|mixes)\//.test(url.pathname)) {
            queueCalls++;
            if (options.queueError && queueCalls <= options.queueError) return route.fulfill({ status: 500, body: '{}' });
            const response = options.queue || (fixture === 'watch-thin' ? JSON.parse(fs.readFileSync(path.join(generated, 'queue-thin.json'))) : queue);
            return route.fulfill({ contentType: 'application/json', body: JSON.stringify(response) });
        }
        if (url.pathname.startsWith('/api/v1/transcripts/')) {
            transcriptCalls++;
            if (options.transcriptError && transcriptCalls <= options.transcriptError) return route.fulfill({ status: 500, body: '{}' });
            return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ transcript: { autoGenerated: url.searchParams.get('label').includes('Indonesian'), body: [
                { type: 'heading', startMs: 0, line: 'Introduction' },
                { type: 'regular', startMs: 80000, line: 'Finding the light <img src=x onerror=alert(1)>' },
                { type: 'regular', startMs: 225000, line: 'Color in motion' }
            ] } }) });
        }
        if (url.pathname === '/js/silvermine-videojs-quality-selector.min.js' && !options.realPlayer) return route.fulfill({ contentType: 'application/javascript', body: '' });
        if (url.pathname === '/js/player.js' && !options.realPlayer) return route.fulfill({ contentType: 'application/javascript', body: playerStub });
        if (url.pathname.startsWith('/videojs/') && !options.realPlayer) return route.fulfill({ contentType: url.pathname.endsWith('.css') ? 'text/css' : 'application/javascript', body: '' });
        if (url.pathname.startsWith('/vi/') || url.pathname.startsWith('/ggpht')) return route.fulfill({ contentType: 'image/svg+xml', body: picture });
        if (options.realPlayer && url.pathname === '/latest_version') {
            const body = fs.readFileSync(path.join(generated, 'fixture.webm'));
            const range = route.request().headers().range;
            const match = range && range.match(/bytes=(\d+)-(\d*)/);
            if (match) {
                const start = Number(match[1]);
                const end = match[2] ? Math.min(Number(match[2]), body.length - 1) : body.length - 1;
                return route.fulfill({ status: 206, contentType: 'video/webm', headers: { 'accept-ranges': 'bytes', 'content-range': `bytes ${start}-${end}/${body.length}` }, body: body.subarray(start, end + 1) });
            }
            return route.fulfill({ contentType: 'video/webm', headers: { 'accept-ranges': 'bytes' }, body });
        }
        if (url.pathname.startsWith('/api/v1/captions/')) return route.fulfill({ contentType: 'text/vtt', body: 'WEBVTT\n\n00:00.000 --> 00:04.000\nFixture captions\n' });
        if (url.pathname === '/themes/fixture-theme/theme.css') return route.fulfill({ contentType: 'text/css', body: 'body { --fixture-theme: active; }' });
        if (/^\/(css|js|fonts|videojs|themes)\//.test(url.pathname)) {
            const file = path.join(root, 'assets', url.pathname);
            if (!fs.existsSync(file)) return route.fulfill({ status: 404, body: '' });
            return route.fulfill({ contentType: url.pathname.endsWith('.css') ? 'text/css' : url.pathname.endsWith('.js') ? 'application/javascript' : url.pathname.endsWith('.svg') ? 'image/svg+xml' : 'application/octet-stream', body: fs.readFileSync(file) });
        }
        return route.fulfill({ contentType: 'application/json', body: '{}' });
    });
    await page.goto('https://invidious.test/' + (options.route || (fixture.startsWith('watch') ? 'watch?v=2isYuQZMbdU&list=PLfixture&index=2' : fixture.startsWith('preferences') ? 'preferences' : fixture.startsWith('search') ? 'search?q=light' : 'feed/popular')));
    return { page, context, errors, requests, queueCalls: () => queueCalls, transcriptCalls: () => transcriptCalls };
}

for (const engine of engines) {
    test(`${engine}: theme cards render and submit without JavaScript`, async () => {
        const { page, context } = await pageFor(engine, { fixture: 'preferences', javascript: false, width: 390 });
        const radio = page.getByRole('radio', { name: 'Modern Neon' });
        assert.equal(await radio.isChecked(), true);
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'modern-neon');
        assert.equal(await page.locator('.theme-option').filter({ has: radio }).locator('.theme-card-selected').isVisible(), true);
        await radio.scrollIntoViewIfNeeded();
        const preview = page.locator('.theme-option').filter({ has: radio }).locator('img');
        await preview.waitFor();
        assert.equal(await preview.evaluate(img => img.complete && img.naturalWidth > 0), true);
        await radio.focus();
        await page.keyboard.press('Space');
        await page.locator('.theme-picker').screenshot({ path: path.join(artifacts, `${engine}-theme-picker.png`) });
        const posted = page.waitForRequest(request => request.method() === 'POST');
        await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
        assert.equal(new URLSearchParams((await posted).postData()).get('theme'), 'modern-neon');
        await context.close();
    });
    test(`${engine}: alternative theme loads in isolation and supports keyboard selection`, async () => {
        const { page, context, requests } = await pageFor(engine, { fixture: 'preferences-alternative' });
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'fixture-theme');
        assert.equal(await page.getByRole('radio', { name: 'Fixture Theme' }).isChecked(), true);
        assert.ok(requests.some(url => url.startsWith('/themes/fixture-theme/theme.css')));
        assert.ok(!requests.some(url => url.startsWith('/themes/modern-neon/theme.css')));
        await page.getByRole('radio', { name: 'Fixture Theme' }).focus();
        await page.keyboard.press('ArrowRight');
        assert.equal(await page.getByRole('radio', { name: 'Modern Neon' }).isChecked(), true);
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'fixture-theme');
        await page.locator('#toggle_theme').click();
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'fixture-theme');
        await context.close();
    });
    test(`${engine}: Diary selection submits without JavaScript and loads alone`, async () => {
        const { page, context, requests } = await pageFor(engine, { fixture: 'preferences-diary', javascript: false, width: 390 });
        const radio = page.getByRole('radio', { name: 'Diary', exact: true });
        assert.equal(await radio.isChecked(), true);
        for (const img of await page.locator('.theme-card img').all()) {
            assert.equal(await img.evaluate(el => el.complete && el.naturalWidth > 0), true);
        }
        assert.ok(requests.some(url => url.startsWith('/themes/diary/theme.css')));
        assert.ok(!requests.some(url => url.startsWith('/themes/modern-neon/theme.css')));
        const posted = page.waitForRequest(request => request.method() === 'POST');
        await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
        assert.equal(new URLSearchParams((await posted).postData()).get('theme'), 'diary');
        await context.close();
    });
    test(`${engine}: Diary palettes, mode toggle and keyboard selection`, async () => {
        for (const [mode, systemTheme, expected] of [['light', 'dark', 'light'], ['dark', 'light', 'dark'], ['auto', 'dark', 'dark'], ['auto', 'light', 'light']]) {
            const { page, context } = await pageFor(engine, { fixture: `browse-diary-${mode}`, systemTheme });
            assert.equal(await page.locator('body').evaluate(el => getComputedStyle(el).colorScheme), expected);
            await page.locator('#toggle_theme').click();
            assert.equal(await page.locator('body').getAttribute('data-theme'), 'diary');
            assert.equal(await page.locator('body').getAttribute('data-density'), 'balanced');
            await context.close();
        }
        const { page, context } = await pageFor(engine, { fixture: 'preferences' });
        await page.getByRole('radio', { name: 'Modern Neon' }).focus();
        await page.keyboard.press('ArrowRight');
        assert.equal(await page.getByRole('radio', { name: 'Diary', exact: true }).isChecked(), true);
        await context.close();
    });
    test(`${engine}: Diary preserves real player controls`, async () => {
        for (const width of [390, 1440]) {
            const { page, context, errors } = await pageFor(engine, { fixture: 'watch-diary-light', realPlayer: true, width, touch: width === 390 });
            await page.waitForFunction(() => window.player && typeof player.play === 'function');
            await page.evaluate(() => { player.muted(true); player.play(); });
            await page.waitForFunction(() => player.currentTime() > 0.1);
            await page.evaluate(() => { player.pause(); player.currentTime(1); player.playbackRate(1.5); });
            assert.equal(await page.evaluate(() => player.paused()), true);
            assert.equal(await page.evaluate(() => player.playbackRate()), 1.5);
            await page.waitForFunction(() => player.currentTime() >= 0.9);
            assert.deepEqual(errors, []);
            await context.close();
        }
    });
    test(`${engine}: Diary responsive paper layouts`, async () => {
        for (const width of [320, 390, 768, 1024, 1440, 1920]) {
            for (const fixture of ['browse-diary-light', 'browse-diary-dark', 'browse-diary-compact', 'browse-diary-thin', 'watch-diary-light', 'watch-diary-dark', 'watch-diary-rtl', 'preferences-diary', 'search-diary', 'playlist-diary', 'history-diary', 'playlist-library-diary', 'login-diary', 'error-diary', 'channel-diary']) {
                const { page, context, errors } = await pageFor(engine, { fixture, width });
                assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${fixture} overflows at ${width}`);
                assert.deepEqual(errors, []);
                if ([320, 1440].includes(width)) {
                    await page.locator('img.thumbnail').evaluateAll(images => Promise.all(images.filter(img => img.getBoundingClientRect().top < innerHeight).map(img => img.decode())));
                    await page.screenshot({ path: path.join(artifacts, `${engine}-${fixture}-${width}.png`) });
                }
                if (fixture === 'browse-diary-light' && width === 320) {
                    await page.addStyleTag({ content: 'html { font-size: 200%; }' });
                    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Diary enlarged text overflows');
                    await page.keyboard.press('Tab');
                    assert.equal(await page.locator('.skip-link').evaluate(el => el === document.activeElement), true);
                }
                await context.close();
            }
        }
    });
    test(`${engine}: actual Video.js player retains playback, seeking and controls`, async () => {
        for (const [width, height, touch] of [[1440, 1000, false], [320, 700, true], [390, 844, true], [768, 1000, true], [844, 390, true], [1024, 768, false]]) {
            const { page, context, errors } = await pageFor(engine, { realPlayer: true, touch, width, height });
            await page.waitForFunction(() => window.player && typeof player.play === 'function');
            await page.evaluate(() => { player.muted(true); player.play(); });
            await page.waitForFunction(() => player.currentTime() > 0.1, { timeout: 10000 });
            await page.evaluate(() => { player.pause(); player.currentTime(1); player.playbackRate(1.5); });
            assert.equal(await page.evaluate(() => player.paused()), true);
            assert.equal(await page.evaluate(() => player.playbackRate()), 1.5);
            await page.waitForFunction(() => player.currentTime() >= 0.9);
            assert.ok(await page.evaluate(() => player.currentTime() >= 0.9));
            assert.equal(await page.locator('.vjs-fullscreen-control').count(), 1);
            assert.equal(await page.locator('button.vjs-captions-button').count(), 1);
            assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
            const playerBox = await page.locator('#player').boundingBox();
            const fullBox = await page.locator('.vjs-fullscreen-control').boundingBox();
            assert.ok(fullBox.width >= 44 && fullBox.height >= 44);
            assert.ok(fullBox.x >= playerBox.x && fullBox.x + fullBox.width <= playerBox.x + playerBox.width + 1);
            assert.equal(await page.locator('.vjs-wide-control').isVisible(), width >= 1100);
            await page.screenshot({ path: path.join(artifacts, `${engine}-actual-player-${width}.png`) });
            if ([390, 1440].includes(width)) await page.screenshot({ path: path.join(artifacts, `${engine}-actual-player-${touch ? 'mobile' : 'desktop'}.png`) });
            assert.deepEqual(errors, []);
            await context.close();
        }
    });

    test(`${engine}: header is horizontal and Library navigation is always available`, async () => {
        const { page, context, errors } = await pageFor(engine, { fixture: 'browse-dark' });
        const rail = page.locator('.navigation-rail');
        for (const feed of ['history', 'subscriptions', 'playlists']) assert.equal(await rail.locator(`a[href="/feed/${feed}"]`).isVisible(), true);
        assert.equal(await rail.locator('a[href="/preferences"]').isVisible(), true);
        assert.equal(await rail.locator('a[href="/"]').count(), 0);
        assert.equal(await page.locator('.index-link').getAttribute('href'), '/');
        assert.equal((await page.locator('.navigation-menu > summary').textContent()).trim(), '☰');
        assert.equal(await page.locator('.user-field a[href*="preferences"]').count(), 0);
        assert.ok((await page.locator('.index-link').boundingBox()).height <= 40);
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator('.navigation-menu > summary').click();
        for (const feed of ['history', 'subscriptions', 'playlists']) assert.equal(await page.locator(`.navigation-menu a[href="/feed/${feed}"]`).isVisible(), true);
        await page.keyboard.press('Escape');
        assert.equal(await page.locator('.navigation-menu').getAttribute('open'), null);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: player wide control, paused idle state and keyboard access`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true });
        await page.evaluate(() => { player.muted(true); player.play(); });
        await page.waitForFunction(() => player.currentTime() > 0.1);
        await page.evaluate(() => player.pause());
        const wide = page.locator('.vjs-wide-control');
        assert.equal(await wide.getAttribute('title'), 'Wide player');
        assert.equal(await page.locator('.watch-actions #wide-player').count(), 0);
        const before = await page.locator('#player-container').boundingBox();
        assert.equal(await wide.getAttribute('aria-pressed'), 'true');
        await wide.click();
        assert.equal(await wide.getAttribute('aria-pressed'), 'false');
        assert.ok((await page.locator('#player-container').boundingBox()).width < before.width);
        await wide.click();
        assert.equal(await wide.getAttribute('aria-pressed'), 'true');
        const wideBox = await wide.boundingBox();
        const fullBox = await page.locator('.vjs-fullscreen-control').boundingBox();
        assert.ok(Math.abs(fullBox.x - (wideBox.x + wideBox.width)) <= 4);
        assert.ok(wideBox.width >= 44 && wideBox.height >= 44);
        await page.mouse.move(0, 0);
        await page.waitForFunction(() => !player.userActive(), null, { timeout: 6000 });
        await page.waitForFunction(() => getComputedStyle(player.controlBar.el()).opacity === '0');
        assert.equal(await page.evaluate(() => player.paused()), true);
        await page.mouse.move(before.x + 100, before.y + 100, { steps: 5 });
        await page.waitForFunction(() => getComputedStyle(player.controlBar.el()).opacity === '1');
        // Keyboard focus must keep the focused control accessible during inactivity.
        await page.keyboard.press('Tab');
        await wide.focus();
        await page.evaluate(() => player.userActive(false));
        assert.equal(await wide.isVisible(), true);
        await page.keyboard.press('Enter');
        assert.equal(await wide.getAttribute('aria-pressed'), 'false');
        assert.equal(await page.evaluate(() => player.paused()), true);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: player menus support transient hover and persistent click modes`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true });
        const button = page.locator('button.vjs-playback-rate');
        const menu = page.locator('.vjs-playback-rate .vjs-menu-content');
        await page.evaluate(() => { player.muted(true); player.play(); });
        await page.waitForFunction(() => player.currentTime() > 0.1);
        await page.evaluate(() => player.userActive(true));
        await button.hover();
        await menu.waitFor({ state: 'visible' });
        await menu.getByText('1.5x', { exact: true }).hover();
        assert.equal(await menu.isVisible(), true);
        await menu.getByText('1.5x', { exact: true }).click();
        await page.waitForFunction(() => player.playbackRate() === 1.5);
        await menu.waitFor({ state: 'hidden' });

        await button.hover();
        await menu.waitFor({ state: 'visible' });
        await page.mouse.move(0, 0);
        await menu.waitFor({ state: 'hidden' });

        await button.click();
        await menu.waitFor({ state: 'visible' });
        await page.mouse.move(0, 0);
        assert.equal(await menu.isVisible(), true);
        await menu.getByText('1.25x', { exact: true }).click();
        await page.waitForFunction(() => player.playbackRate() === 1.25);
        await menu.waitFor({ state: 'hidden' });
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: cached history titles and compact desktop playlist library`, async () => {
        const history = await pageFor(engine, { fixture: 'history' });
        const cards = history.page.locator('.media-card');
        assert.match(await cards.nth(0).textContent(), /A journey through light/);
        assert.match(await cards.nth(1).textContent(), /Light <study> & color/);
        assert.equal(await cards.nth(2).locator('p').count(), 0);
        assert.equal(await cards.nth(2).locator('img').count(), 1);
        assert.equal(history.requests.some(url => url.startsWith('/api/v1/videos/')), false);
        assert.deepEqual(history.errors, []);
        await history.context.close();
        const library = await pageFor(engine, { fixture: 'playlist-library' });
        const image = library.page.locator('.playlist-library img').first();
        assert.ok((await image.boundingBox()).width < 420);
        await library.page.setViewportSize({ width: 390, height: 844 });
        assert.ok((await image.boundingBox()).width > 300);
        assert.deepEqual(library.errors, []);
        await library.context.close();
    });

    test(`${engine}: mobile paused controls hide, wake on tap, and keep menus usable`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true, touch: true, width: 390, height: 844 });
        await page.evaluate(() => { player.muted(true); player.play(); });
        await page.waitForFunction(() => player.currentTime() > 0.1);
        await page.evaluate(() => player.pause());
        await page.waitForFunction(() => !player.userActive(), null, { timeout: 6000 });
        await page.locator('.mobile-operations-bar').waitFor({ state: 'hidden' });
        const box = await page.locator('#player').boundingBox();
        await page.touchscreen.tap(box.x + box.width / 2, box.y + box.height / 2);
        await page.waitForFunction(() => player.userActive());
        await page.locator('.mobile-operations-bar').waitFor({ state: 'visible' });
        assert.equal(await page.locator('.mobile-operations-bar').isVisible(), true);
        assert.equal(await page.evaluate(() => player.paused()), true);
        await page.locator('button.vjs-playback-rate').tap();
        const menu = page.locator('.vjs-playback-rate .vjs-menu');
        await menu.locator('.vjs-menu-content').waitFor({ state: 'visible', timeout: 3000 });
        await page.evaluate(() => player.userActive(false));
        assert.equal(await menu.locator('.vjs-menu-content').isVisible(), true);
        const menuBox = await menu.locator('.vjs-menu-content').boundingBox();
        assert.ok(menuBox.x >= box.x && menuBox.x + menuBox.width <= box.x + box.width + 1);
        assert.ok(menuBox.y + menuBox.height <= box.y + box.height + 1);
        await page.screenshot({ path: path.join(artifacts, `${engine}-player-mobile-menu.png`) });
        await menu.getByText('1.5x', { exact: true }).tap();
        await page.waitForFunction(() => player.playbackRate() === 1.5, null, { timeout: 3000 });
        await menu.locator('.vjs-menu-content').waitFor({ state: 'hidden' });
        assert.equal(await page.evaluate(() => player.playbackRate()), 1.5);
        assert.equal(await page.evaluate(() => player.paused()), true);
        await page.setViewportSize({ width: 320, height: 700 });
        await page.locator('button.vjs-playback-rate').tap();
        await menu.locator('.vjs-menu-content').waitFor({ state: 'visible' });
        const smallPlayer = await page.locator('#player').boundingBox();
        const smallMenu = await menu.locator('.vjs-menu-content').boundingBox();
        assert.ok(smallMenu.y + smallMenu.height <= smallPlayer.y + smallPlayer.height + 1);
        await menu.getByText('1.5x', { exact: true }).tap();
        await menu.locator('.vjs-menu-content').waitFor({ state: 'hidden' });
        assert.equal(await page.evaluate(() => player.playbackRate()), 1.5);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: mobile video taps toggle all controls while playing`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true, touch: true, mobileUserAgent: true, width: 390, height: 844 });
        await page.evaluate(() => { player.muted(true); player.play(); });
        await page.waitForFunction(() => player.currentTime() > 0.1);
        await page.waitForFunction(() => !player.userActive(), null, { timeout: 6000 });
        const box = await page.locator('#player').boundingBox();
        await page.touchscreen.tap(box.x + box.width / 2, box.y + box.height / 3);
        await page.waitForFunction(() => player.userActive());
        await page.locator('.vjs-touch-overlay.show-play-toggle').waitFor({ state: 'attached' });
        await page.locator('.mobile-operations-bar').waitFor({ state: 'visible' });
        assert.equal(await page.locator('.mobile-operations-bar').isVisible(), true);
        await page.touchscreen.tap(box.x + box.width / 4, box.y + box.height / 3);
        await page.waitForFunction(() => !player.userActive());
        await page.locator('.mobile-operations-bar').waitFor({ state: 'hidden' });
        await page.waitForFunction(() => getComputedStyle(document.querySelector('.vjs-touch-overlay .vjs-play-control')).opacity === '0');
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: queue selects a repeated occurrence, and keeps recommendations separate`, async () => {
        const { page, context, errors } = await pageFor(engine);
        await page.waitForSelector('.queue-row a[aria-current]');
        assert.equal(await page.locator('.queue-row:has([aria-current])').getAttribute('data-index'), '2');
        assert.equal(await page.locator('.queue-row [aria-current]').count(), 1);
        assert.match(await page.locator('[data-direction=previous]').getAttribute('href'), /index=1/);
        assert.match(await page.locator('[data-direction=next]').getAttribute('href'), /index=3/);
        assert.equal(await page.locator('#queue-title').textContent(), 'Light & motion <study>');
        assert.equal(await page.locator('.recommendations a[href*="list="]').count(), 0);
        assert.equal(await page.evaluate(() => window.__ended.length), 1);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: queue failure is retryable and does not enable recommendation autoplay`, async () => {
        const { page, context, errors } = await pageFor(engine, { queueError: 1 });
        await page.waitForSelector('#queue-retry:not([hidden])');
        assert.equal(await page.evaluate(() => window.__ended.length), 0);
        await page.locator('#queue-retry').click();
        await page.waitForSelector('.queue-row [aria-current]');
        assert.equal(await page.evaluate(() => window.__ended.length), 1);
        await page.evaluate(() => get_playlist('PLfixture'));
        await page.waitForSelector('.queue-row [aria-current]');
        assert.equal(await page.evaluate(() => window.__ended.length), 1);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: missing, empty and ended queues do not attach an advancement handler`, async () => {
        for (const response of [{ playlistHtml: '<ol></ol>', nextVideo: null }, { ...queue, nextVideo: null }]) {
            const { page, context, errors } = await pageFor(engine, { queue: response });
            await page.waitForFunction(() => document.getElementById('playlist').getAttribute('aria-busy') === 'false');
            assert.equal(await page.evaluate(() => window.__ended.length), 0);
            assert.equal(await page.locator('[data-direction=next]').count(), 0);
            assert.ok(await page.locator('#queue-status').textContent());
            assert.deepEqual(errors, []);
            await context.close();
        }
    });

    test(`${engine}: transcript loads on demand, searches safely, seeks, caches, and retries`, async () => {
        const { page, context, errors, requests, transcriptCalls } = await pageFor(engine, { transcriptError: 1 });
        assert.equal(transcriptCalls(), 0);
        assert.equal(requests.some(url => url.startsWith('/js/transcript.js')), false);
        await page.locator('#transcript-panel > summary').click();
        await page.waitForSelector('#transcript-retry:not([hidden])');
        await page.locator('#transcript-retry').click();
        await page.waitForSelector('.transcript-line');
        assert.equal(await page.locator('.transcript-line img').count(), 0);
        await page.locator('#transcript-search').fill('Finding');
        assert.equal(await page.locator('.transcript-line').count(), 1);
        await page.locator('.transcript-line button').click();
        assert.equal(await page.evaluate(() => window.__time), 80);
        await page.locator('#transcript-search').fill('not present');
        assert.equal(await page.locator('#transcript-status').textContent(), 'No matching transcript lines.');
        await page.locator('#transcript-search').fill('');
        await page.locator('#transcript-language').selectOption({ index: 1 });
        await page.waitForFunction(() => document.getElementById('transcript-status').textContent.includes('Automatically'));
        await page.locator('#transcript-language').selectOption({ index: 0 });
        assert.equal(transcriptCalls(), 3);
        await page.locator('#timestamp-list a').nth(1).click();
        assert.equal(await page.evaluate(() => window.__time), 80);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: mobile queue is immediately below player, collapsible, and keyboard operable`, async () => {
        const { page, context, errors } = await pageFor(engine, { width: 390 });
        await page.waitForSelector('.queue-row', { state: 'attached' });
        assert.equal(await page.locator('#playlist').isVisible(), false);
        const player = await page.locator('#player-container').boundingBox();
        const panel = await page.locator('#playlist-panel').boundingBox();
        const title = await page.locator('.watch-heading').boundingBox();
        assert.ok(player.y + player.height <= panel.y + 1);
        assert.ok(panel.y + panel.height <= title.y + 1);
        await page.locator('#queue-toggle').focus();
        await page.keyboard.press('Enter');
        assert.equal(await page.locator('#playlist').isVisible(), true);
        assert.equal(await page.locator('#queue-toggle').getAttribute('aria-expanded'), 'true');
        assert.equal(await page.evaluate(() => document.activeElement.id), 'queue-toggle');
        await page.evaluate(() => {
            const list = document.getElementById('playlist');
            const rows = list.querySelector('ol');
            for (let i = 0; i < 8; i++) rows.appendChild(rows.lastElementChild.cloneNode(true));
            list.scrollTop = list.scrollHeight;
        });
        const scroll = await page.locator('#playlist').evaluate(el => el.scrollTop);
        assert.ok(scroll > 0);
        await page.setViewportSize({ width: 390, height: 800 });
        await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
        assert.equal(await page.locator('#playlist').evaluate(el => el.scrollTop), scroll);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: theme switching preserves density and page layout`, async () => {
        const { page, context, errors } = await pageFor(engine, { fixture: 'browse-compact' });
        await page.locator('#toggle_theme').click();
        assert.equal(await page.locator('body').getAttribute('data-density'), 'compact');
        assert.equal(await page.locator('body').getAttribute('class'), 'light-theme');
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: no-JavaScript and thin modes retain essential navigation`, async () => {
        const nojs = await pageFor(engine, { javascript: false });
        assert.equal(await nojs.page.locator('#queue-title').isVisible(), true);
        assert.equal(await nojs.page.locator('#share-video').isVisible(), false);
        assert.equal(await nojs.page.locator('#transcript-panel').isVisible(), false);
        if (await nojs.page.locator('#description-box').getAttribute('open') === null) await nojs.page.locator('#description-box > summary').click();
        assert.equal(await nojs.page.locator('#descriptionWrapper').isVisible(), true);
        await nojs.context.close();
        const thin = await pageFor(engine, { fixture: 'watch-thin' });
        await thin.page.waitForSelector('.queue-row');
        assert.equal(await thin.page.locator('.queue-row img, .recommendation img').count(), 0);
        assert.deepEqual(thin.errors, []);
        await thin.context.close();
    });

    test(`${engine}: responsive layouts and representative visual snapshots`, async () => {
        for (const fixture of ['watch-dark', 'watch-light', 'watch-rtl', 'browse-dark', 'browse-light', 'browse-compact', 'browse-signed-in', 'preferences', 'history', 'playlist-library']) {
            const session = await pageFor(engine, { fixture });
            for (const width of [320, 390, 768, 1024, 1440, 1920]) {
                await session.page.setViewportSize({ width, height: 1000 });
                await session.page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
                assert.ok(await session.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${fixture} overflows at ${width}px`);
                if ([390, 1440].includes(width)) await session.page.screenshot({ path: path.join(artifacts, `${engine}-${fixture}-${width}.png`), fullPage: true });
            }
            assert.deepEqual(session.errors, [], fixture);
            await session.context.close();
        }
    });

    test(`${engine}: enlarged text and phone landscape keep navigation usable`, async () => {
        for (const fixture of ['watch-dark', 'browse-signed-in', 'preferences']) {
            const { page, context, errors } = await pageFor(engine, { fixture, width: 390 });
            await page.evaluate(() => document.documentElement.style.fontSize = '200%');
            await page.evaluate(() => document.fonts.ready);
            await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
            const overflow = await page.evaluate(() => Array.from(document.querySelectorAll('body *')).filter(el => {
                const box = el.getBoundingClientRect();
                return box.width && box.right > innerWidth + 1;
            }).slice(0, 8).map(el => `${el.tagName}.${el.className}#${el.id}`));
            assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${fixture}: enlarged text ${overflow.join(', ')}`);
            await page.evaluate(() => document.documentElement.style.fontSize = '');
            await page.setViewportSize({ width: 844, height: 390 });
            await page.locator('.navigation-menu > summary').click();
            assert.equal(await page.locator('.navigation-menu a[href="/feed/subscriptions"]').isVisible(), true);
            assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${fixture}: landscape`);
            assert.deepEqual(errors, []);
            await context.close();
        }
    });
}

test('library navigation survives custom feed settings without channel management links', () => {
    const html = fs.readFileSync(path.join(generated, 'navigation-subscribed.html'), 'utf8');
    for (const feed of ['history', 'subscriptions', 'playlists']) assert.ok(html.includes(`href="/feed/${feed}"`));
    assert.ok(html.includes('href="/feed/subscriptions" aria-current=page'));
    assert.ok(!html.includes('/subscription_manager'));
    assert.ok(!html.includes('/channel/'));
    assert.ok(!html.includes('<img'));
});

test('UI asset additions stay below the 30KB compressed initial-load budget', () => {
    const baseline = require('./asset-baseline.json');
    let delta = 0;
    for (const [file, originalBytes] of Object.entries(baseline.gzipBytes)) {
        const current = fs.readFileSync(path.join(root, 'assets', file));
        delta += gzipSync(current).length - originalBytes;
    }
    delta += gzipSync(fs.readFileSync(path.join(root, 'assets/js/dearrow.js'))).length;
    assert.ok(delta <= 30 * 1024, `${delta} bytes added`);
    console.log(`Initial UI asset increase: ${delta} gzip bytes; transcript loaded on demand.`);
});

// Picker previews are lazy-loaded on preferences, not part of the site-wide CSS/JS budget.
test('Theme preview images stay below the 24KB compressed budget', () => {
    const baseline = require('./asset-baseline.json');
    let delta = 0;
    for (const [file, originalBytes] of Object.entries(baseline.previewGzipBytes)) {
        delta += gzipSync(fs.readFileSync(path.join(root, 'assets', file))).length - originalBytes;
    }
    assert.ok(delta <= 24 * 1024, `${delta} preview bytes added`);
});

for (const engine of engines) {
    test(`${engine}: video menus support keyboard dismissal and signed-out sign-in links`, async () => {
        const { page, context, errors } = await pageFor(engine, { fixture: 'browse-dark' });
        const menu = page.locator('.video-context').first();
        await menu.locator('summary').focus();
        await page.keyboard.press('ArrowDown');
        assert.equal(await menu.getAttribute('open'), '');
        await page.waitForFunction(() => document.querySelector('.video-context[open] .video-context-actions a') === document.activeElement);
        assert.equal(await menu.locator('a').first().evaluate(el => el === document.activeElement), true);
        assert.match(await menu.locator('a').first().getAttribute('href'), /^\/login\?referer=/);
        await page.keyboard.press('Escape');
        assert.equal(await menu.getAttribute('open'), null);
        assert.equal(await menu.locator('summary').evaluate(el => el === document.activeElement), true);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: block removes discovery cards only after success and Undo restores them`, async () => {
        const { page, context } = await pageFor(engine, { fixture: 'browse-signed-in' });
        let fail = true;
        const changes = [];
        await page.route('**/blocked_channels?*', route => {
            changes.push(new URLSearchParams(route.request().postData()));
            return route.fulfill({ status: fail ? 500 : 200, contentType: 'application/json', body: '{}' });
        });
        const menu = page.locator('.video-context').first();
        await menu.locator('summary').click();
        await menu.locator('[data-video-action=block]').click();
        await page.locator('#video-actions-notice').waitFor({ state: 'visible' });
        assert.equal(await page.locator('.media-item:visible').count(), 12);
        fail = false;
        await menu.locator('summary').click();
        await menu.locator('[data-video-action=block]').click();
        await page.locator('#video-actions-undo').waitFor({ state: 'visible' });
        assert.equal(await page.locator('.media-item:visible').count(), 0);
        await page.locator('#video-actions-undo').click();
        await page.locator('.media-item').first().waitFor({ state: 'visible' });
        assert.equal(await page.locator('.media-item:visible').count(), 12);
        assert.deepEqual(changes.map(p => p.get('action')), ['block', 'block', 'unblock']);
        assert.equal(changes[1].get('csrf_token'), 'fixture-token');
        await context.close();
    });

    test(`${engine}: playlist creation retains the created playlist when adding fails`, async () => {
        const { page, context, errors } = await pageFor(engine, { fixture: 'browse-signed-in', width: 390 });
        await page.route('**/video_actions', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ playlists: [{ id: 'IVexisting', title: 'Existing' }], defaultPlaylist: 'IVexisting' }) }));
        let creations = 0;
        await page.route('**/create_playlist?*', route => {
            creations++;
            const body = new URLSearchParams(route.request().postData());
            assert.equal(body.get('privacy'), 'Private');
            return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ playlistId: 'IVnew', title: 'New playlist' }) });
        });
        let saves = 0;
        await page.route('**/playlist_ajax?*', route => {
            saves++;
            assert.equal(new URL(route.request().url()).searchParams.get('playlist_id'), 'IVnew');
            return route.fulfill({ status: saves === 1 ? 500 : 200, contentType: 'application/json', body: '{}' });
        });
        const menu = page.locator('.video-context').first();
        await menu.locator('summary').click();
        await menu.locator('[data-video-action=playlist]').click();
        await page.waitForFunction(() => document.getElementById('video-playlist-select').value === 'IVexisting');
        await page.locator('#video-playlist-create-details > summary').click();
        await page.locator('#video-playlist-title').fill('New playlist');
        await page.locator('#video-playlist-create button').click();
        await page.waitForFunction(() => document.getElementById('video-playlist-status').textContent.includes('retry'));
        assert.equal(await page.locator('#video-playlist-select').inputValue(), 'IVnew');
        await page.locator('#video-playlist-save [type=submit]').click();
        await page.waitForFunction(() => document.getElementById('video-playlist-status').textContent === document.getElementById('video-actions-config').dataset.saved);
        assert.equal(creations, 1);
        assert.equal(saves, 2);
        const box = await page.locator('#video-playlist-dialog').boundingBox();
        assert.ok(box.x >= 0 && box.x + box.width <= 390);
        await page.keyboard.press('Escape');
        assert.equal(await menu.locator('summary').evaluate(el => el === document.activeElement), true);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: search Filters owns the override and filtered-empty pages retain pagination`, async () => {
        const { page, context } = await pageFor(engine, { fixture: 'search-blocked' });
        await page.locator('#filters-collapse > summary').click();
        const toggle = page.locator('#filters input[name=include_blocked]');
        assert.equal(await toggle.isChecked(), false);
        assert.equal(await page.locator('#filters input[name=page]').inputValue(), '1');
        assert.ok(await page.locator('a[href*="page=3"]').count() > 0);
        assert.ok(await page.locator('.no-results-error a[href*="include_blocked=1"]').count() > 0);
        await context.close();
        const included = await pageFor(engine, { fixture: 'search-included' });
        await included.page.locator('#filters-collapse > summary').click();
        assert.equal(await included.page.locator('#filters input[name=include_blocked]').isChecked(), true);
        assert.match(await included.page.locator('a[href*="page=3"]').first().getAttribute('href'), /include_blocked=1/);
        await included.context.close();
    });

    test(`${engine}: blocking the next recommendation updates autoplay and Undo restores it`, async () => {
        const { page, context, errors } = await pageFor(engine, { fixture: 'watch-actions' });
        await page.route('**/blocked_channels?*', route => route.fulfill({ contentType: 'application/json', body: '{}' }));
        const first = page.locator('.recommendation').first();
        const videoId = await first.getAttribute('data-video-id');
        const channelId = await first.getAttribute('data-channel-id');
        const expected = await page.locator('.recommendation').evaluateAll((cards, channel) => cards.find(card => card.dataset.channelId !== channel)?.dataset.videoId || null, channelId);
        await first.locator('.video-context > summary').click();
        await first.locator('[data-video-action=block]').click();
        await page.locator('#video-actions-undo').waitFor({ state: 'visible' });
        assert.equal(await page.evaluate(() => video_data.next_video), expected);
        await page.locator('#video-actions-undo').click();
        await first.waitFor({ state: 'visible' });
        assert.equal(await page.evaluate(() => video_data.next_video), videoId);
        assert.deepEqual(errors, []);
        await context.close();
    });
}

for (const engine of engines) {
    test(`${engine}: blocking leaves subscribed and explicitly included search results visible`, async () => {
        for (const routePath of ['feed/subscriptions', 'playlist?list=IVsaved', 'search?q=light&include_blocked=1']) {
            const { page, context } = await pageFor(engine, { fixture: 'browse-signed-in', route: routePath });
            await page.route('**/blocked_channels?*', route => route.fulfill({ contentType: 'application/json', body: '{}' }));
            const menu = page.locator('.video-context').first();
            await menu.locator('summary').click();
            await menu.locator('[data-video-action=block]').click();
            await page.locator('#video-actions-undo').waitFor({ state: 'visible' });
            assert.equal(await page.locator('.media-item:visible').count(), 12);
            assert.equal(await menu.locator('[data-video-action=unblock]').count(), 1);
            await context.close();
        }
    });

    test(`${engine}: blocking the only remaining recommendation disables autoplay`, async () => {
        const { page, context } = await pageFor(engine, { fixture: 'watch-actions' });
        await page.route('**/blocked_channels?*', route => route.fulfill({ contentType: 'application/json', body: '{}' }));
        await page.locator('.recommendation').evaluateAll(cards => cards.slice(1).forEach(card => card.remove()));
        const menu = page.locator('.recommendation .video-context').first();
        await menu.locator('summary').click();
        await menu.locator('[data-video-action=block]').click();
        await page.locator('#video-actions-undo').waitFor({ state: 'visible' });
        assert.equal(await page.evaluate(() => video_data.next_video), null);
        assert.equal(await page.evaluate(() => window.__ended.includes(next_video)), false);
        await context.close();
    });

    test(`${engine}: video menus stay within mobile and compact viewports`, async () => {
        for (const fixture of ['browse-compact', 'watch-dark']) {
            const { page, context, errors } = await pageFor(engine, { fixture, width: 390 });
            const menu = page.locator('.video-context').first();
            await menu.locator('summary').click();
            const panel = menu.locator('.video-context-actions');
            await panel.waitFor({ state: 'visible' });
            await page.waitForFunction(() => {
                var panel = document.querySelector('.video-context[open] .video-context-actions');
                if (!panel || panel.dataset.positioned !== 'true') return false;
                var box = panel.getBoundingClientRect();
                return box.x >= 0 && box.y >= 0 && box.right <= innerWidth && box.bottom <= innerHeight;
            });
            const box = await panel.boundingBox();
            assert.deepEqual(errors, []);
            assert.ok(box.x >= 0 && box.x + box.width <= 390 && box.y >= 0 && box.y + box.height <= 1000, JSON.stringify({ box, style: await panel.getAttribute('style'), viewport: await page.evaluate(() => [innerWidth, innerHeight]) }));
            assert.deepEqual(await panel.evaluate(el => {
                var box = el.getBoundingClientRect();
                var overlaps = [];
                for (var y = box.top + 10; y < box.bottom - 10; y += 10) {
                    var hit = document.elementFromPoint(box.left + box.width / 2, y);
                    if (!el.contains(hit)) overlaps.push(hit ? hit.outerHTML.slice(0, 150) : 'outside viewport');
                }
                return overlaps;
            }), [], 'Thumbnail overlays must not cover the menu: ' + fixture);
            await panel.screenshot({ path: path.join(artifacts, `${engine}-${fixture}-video-menu.png`) });
            await context.close();
        }
    });

    test(`${engine}: control-bar transparency preserves opaque controls on bright and dark video`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true });
        for (const color of ['#eeeeee', '#111111']) {
            await page.evaluate(color => {
                var video = document.querySelector('video');
                player.hasStarted(true);
                player.pause();
                player.poster('');
                video.style.opacity = '0';
                player.el().style.backgroundColor = color;
                player.userActive(true);
                player.controlBar.el().style.opacity = '1';
            }, color);
            const bar = page.locator('.vjs-control-bar');
            await bar.waitFor({ state: 'visible' });
            assert.match(await bar.evaluate(el => getComputedStyle(el).backgroundColor), /0\.2\)/);
            assert.equal(await page.locator('.vjs-fullscreen-control').evaluate(el => getComputedStyle(el).opacity), '1');
            await page.locator('#player-container').screenshot({ path: path.join(artifacts, `${engine}-transparent-controls-${color.slice(1)}.png`) });
        }
        assert.deepEqual(errors, []);
        await context.close();
    });
}

for (const engine of engines) {
    test(`${engine}: owned queue removes a specific occurrence and keeps playback running`, async () => {
        for (const [removePosition, fixture, currentIndex, currentRemoved, nextIndex] of [
            [0, 'queue-removed-before', 1, false, 2],
            [2, 'queue-removed-current', 2, true, 2],
            [3, 'queue-removed-next', 2, false, null]
        ]) {
            const initial = JSON.parse(fs.readFileSync(path.join(generated, 'queue-editable.json')));
            const { page, context, errors } = await pageFor(engine, { fixture: 'watch-owned', queue: initial, route: 'watch?v=2isYuQZMbdU&list=IVfixture&index=2', width: 390 });
            await page.locator('#queue-toggle').click();
            await page.locator('.queue-remove').first().waitFor({ state: 'visible' });
            if (removePosition === 2) await page.locator('#playlist-panel').screenshot({ path: path.join(artifacts, `${engine}-editable-watch-queue.png`) });
            await page.evaluate(() => player.currentTime(123));
            let posts = 0;
            let fail = true;
            const gets = [];
            await page.route('**/api/v1/playlists/IVfixture?*', route => {
                gets.push(new URL(route.request().url()));
                return route.fulfill({ contentType: 'application/json', body: fs.readFileSync(path.join(generated, fixture + '.json'), 'utf8') });
            });
            await page.route('**/playlist_ajax?*', route => {
                posts++;
                const url = new URL(route.request().url());
                assert.equal(url.searchParams.get('action'), 'remove_video');
                assert.equal(url.searchParams.get('playlist_id'), 'IVfixture');
                assert.equal(url.searchParams.get('set_video_id'), String(9007199254740993n + BigInt(removePosition)));
                assert.equal(new URLSearchParams(route.request().postData()).get('csrf_token'), 'fixture-token');
                return route.fulfill({ status: fail ? 500 : 200, contentType: 'application/json', body: '{}' });
            });
            await page.locator('.queue-row').nth(removePosition).locator('.queue-remove').click();
            await page.waitForFunction(() => document.getElementById('queue-status').textContent === watch_ui.queue_remove_error);
            assert.equal(await page.locator('.queue-row').count(), 4);
            assert.equal(await page.evaluate(() => window.__ended.length), 1);
            fail = false;
            await page.locator('.queue-row').nth(removePosition).locator('.queue-remove').click();
            await page.waitForFunction(() => document.querySelectorAll('.queue-row').length === 3);
            assert.equal(posts, 2);
            assert.equal(await page.evaluate(() => player.currentTime()), 123);
            assert.equal(await page.evaluate(() => video_data.index), currentIndex);
            assert.equal(await page.evaluate(() => video_data.playlist_current_removed), currentRemoved);
            assert.equal(await page.locator('.queue-row [aria-current]').count(), currentRemoved ? 0 : 1);
            assert.equal(gets[0].searchParams.get('current_removed'), currentRemoved ? '1' : null);
            if (nextIndex === null) {
                assert.equal(await page.locator('#queue-navigation [data-direction=next]').count(), 0);
                assert.equal(await page.evaluate(() => window.__ended.length), 0);
            } else {
                assert.equal(new URL(await page.locator('#queue-navigation [data-direction=next]').getAttribute('href'), 'https://invidious.test').searchParams.get('index'), String(nextIndex));
                assert.equal(await page.evaluate(() => window.__ended.length), 1);
            }
            assert.deepEqual(errors, []);
            await context.close();
        }
        const readonly = await pageFor(engine);
        await readonly.page.locator('.queue-row').first().waitFor();
        assert.equal(await readonly.page.locator('.queue-remove').count(), 0);
        await readonly.context.close();
    });

    test(`${engine}: mobile center play and control bars share visibility through play, pause, idle and seeking`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true, touch: true, mobileUserAgent: true, width: 390, height: 844 });
        await page.evaluate(() => { player.muted(true); player.loop(true); player.play(); });
        await page.waitForFunction(() => player.currentTime() > 0.1);
        await page.evaluate(() => { player.pause(); player.userActive(true); });
        const center = page.locator('.vjs-touch-overlay .vjs-play-control');
        await center.waitFor({ state: 'visible' });
        await page.waitForFunction(() => getComputedStyle(document.querySelector('.vjs-touch-overlay .vjs-play-control')).opacity === '1');
        // This is the reported bug: pressing the center Play button must not hide it alone.
        await center.tap();
        await page.waitForFunction(() => !player.paused());
        await page.waitForFunction(() => player.currentTime() > 0.2);
        async function sameVisibility(expected) {
            await page.waitForFunction(expected => {
                const nodes = [...document.querySelectorAll('.vjs-control-bar'), document.querySelector('.vjs-touch-overlay .vjs-play-control')];
                return nodes.every(el => getComputedStyle(el).opacity === expected);
            }, expected);
        }
        await sameVisibility('1');
        await page.locator('#player-container').screenshot({ path: path.join(artifacts, `${engine}-mobile-controls-together.png`) });
        const durations = await page.locator('.vjs-control-bar, .vjs-touch-overlay .vjs-play-control').evaluateAll(nodes => nodes.map(el => getComputedStyle(el).transition));
        assert.equal(new Set(durations).size, 1);
        // The plugin emits playing and removes its independent class; visibility stays tied.
        await page.evaluate(() => player.trigger('playing'));
        await sameVisibility('1');
        await page.evaluate(() => { document.activeElement.blur(); player.userActive(false); });
        await sameVisibility('0');
        const box = await page.locator('#player').boundingBox();
        await page.touchscreen.tap(box.x + box.width / 4, box.y + box.height / 3);
        await sameVisibility('1');
        await center.tap();
        await page.waitForFunction(() => player.paused());
        await sameVisibility('1');
        await page.waitForFunction(() => !player.userActive(), null, { timeout: 6000 });
        await sameVisibility('0');
        await page.touchscreen.tap(box.x + box.width / 4, box.y + box.height / 3);
        await sameVisibility('1');
        await page.evaluate(() => player.getChild('TouchOverlay').handleDoubleTap({ changedTouches: [{ clientX: player.el().getBoundingClientRect().right - 10 }] }));
        assert.equal(await page.locator('.vjs-touch-overlay').evaluate(el => getComputedStyle(el).animationName), 'none');
        await sameVisibility('1');
        assert.deepEqual(errors, []);
        await context.close();
    });
}

for (const engine of engines) {
    test(`${engine}: playback shortcuts work from page content and respect interactive controls`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true });
        await page.waitForFunction(() => typeof player !== 'undefined');
        await page.evaluate(() => player.load());
        await page.waitForFunction(() => player.readyState() >= 1);
        await page.evaluate(() => {
            player.pause();
            player.volume(0.5);
            document.activeElement.blur();
        });
        await page.keyboard.press('Space');
        await page.waitForFunction(() => !player.paused());
        await page.keyboard.press('Space');
        await page.waitForFunction(() => player.paused());
        await page.keyboard.press('ArrowUp');
        assert.ok(Math.abs(await page.evaluate(() => player.volume()) - 0.6) < 0.01);
        await page.keyboard.press('ArrowDown');
        assert.ok(Math.abs(await page.evaluate(() => player.volume()) - 0.5) < 0.01);
        await page.evaluate(() => player.currentTime(1));
        await page.keyboard.press('ArrowRight');
        await page.waitForFunction(() => Math.abs(player.currentTime() - Math.min(6, player.duration())) < 0.1);
        await page.keyboard.press('ArrowLeft');
        assert.ok(await page.evaluate(() => player.currentTime()) < 2);
        const input = page.locator('input[name="q"]').first();
        await input.focus();
        await page.keyboard.press('Space');
        await page.keyboard.press('ArrowUp');
        assert.equal(await page.evaluate(() => player.paused()), true);
        assert.ok(Math.abs(await page.evaluate(() => player.volume()) - 0.5) < 0.01);
        const menu = page.locator('.video-context').first();
        await menu.locator('summary').focus();
        await page.keyboard.press('ArrowDown');
        await page.waitForFunction(() => document.activeElement.closest('.video-context-actions'));
        assert.ok(Math.abs(await page.evaluate(() => player.volume()) - 0.5) < 0.01);
        assert.deepEqual(errors, []);
        await context.close();
    });
}

for (const engine of engines) {
    test(`${engine}: DeArrow replaces titles safely, deduplicates queues, and exposes originals`, async () => {
        const {page, context, requests, errors} = await pageFor(engine, {fixture: 'watch-dearrow'});
        const replacement = 'A clear title <img src=x onerror=alert(1)>';
        await page.waitForFunction(() => document.querySelector('[data-dearrow-watch]').textContent.startsWith('A clear title'));
        assert.equal(await page.title(), replacement + ' - Invidious');
        assert.equal(await page.locator('[data-dearrow-watch] img').count(), 0);
        const heading = page.locator('[data-dearrow-watch]');
        await heading.focus();
        const tooltip = page.locator('#' + await heading.getAttribute('aria-describedby'));
        assert.equal(await tooltip.isVisible(), true);
        assert.match(await tooltip.textContent(), /A journey through light, color, and motion/);
        await page.keyboard.press('Escape');
        assert.equal(await tooltip.isVisible(), false);
        await heading.hover();
        assert.equal(await tooltip.isVisible(), true);
        await page.locator('.queue-row').first().waitFor();
        const id = '2isYuQZMbdU';
        const duplicate = page.locator('#playlist [data-dearrow-id="' + id + '"]').first();
        await duplicate.scrollIntoViewIfNeeded();
        await page.waitForFunction(() => document.querySelector('#playlist [data-dearrow-id="2isYuQZMbdU"]').textContent.startsWith('A clear title'));
        assert.equal(requests.filter(url => url === '/api/v1/dearrow/' + id).length, 1);
        assert.equal(await page.locator('.queue-playing').count(), 1);
        assert.ok((await page.locator('.recommendation img').first().getAttribute('src')).startsWith('/vi/'));
        await page.evaluate(() => get_playlist('PLfixture'));
        await page.waitForFunction(() => document.querySelector('#playlist [data-dearrow-id="2isYuQZMbdU"]')?.textContent.startsWith('A clear title'));
        assert.equal(requests.filter(url => url === '/api/v1/dearrow/' + id).length, 1);
        assert.deepEqual(errors, []);
        const tooltipsBefore = await page.locator('.dearrow-tooltip').count();
        await page.evaluate(() => {
            window.removedRecommendation = document.querySelector('.recommendation');
            window.removedRecommendation.remove();
        });
        await page.waitForFunction(count => document.querySelectorAll('.dearrow-tooltip').length < count, tooltipsBefore);
        await page.evaluate(() => document.querySelector('.recommendations').appendChild(window.removedRecommendation));
        const restored = page.locator('.recommendation').last().locator('h3 a');
        await restored.scrollIntoViewIfNeeded();
        await page.waitForFunction(() => window.removedRecommendation.querySelector('[data-dearrow-id]').textContent.startsWith('A clear title'));
        await restored.focus();
        assert.equal(await page.locator('#' + await restored.getAttribute('aria-describedby')).isVisible(), true);
        await page.screenshot({path: path.join(artifacts, `${engine}-dearrow-desktop.png`)});
        await context.close();
    });

    test(`${engine}: DeArrow covers video lists on mobile without original tooltips`, async () => {
        const {page, context, errors} = await pageFor(engine, {fixture: 'browse-dearrow-no-original', width: 390});
        await page.waitForFunction(() => Array.from(document.querySelectorAll('[data-dearrow-id]')).some(el => el.textContent.startsWith('A clear title')));
        assert.equal(await page.locator('.dearrow-tooltip').count(), 0);
        assert.equal(await page.locator('[data-dearrow-id] img').count(), 0);
        await page.screenshot({path: path.join(artifacts, `${engine}-dearrow-mobile.png`)});
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: DeArrow disabled, missing, failed and no-JavaScript modes retain originals`, async () => {
        for (const options of [{fixture: 'watch-dark'}, {fixture: 'watch-dearrow', javascript: false}, {fixture: 'watch-dearrow', dearrowError: true}, {fixture: 'watch-dearrow', dearrowMissing: true}]) {
            const {page, context, requests, errors} = await pageFor(engine, options);
            await page.waitForLoadState('networkidle');
            assert.equal(await page.locator('h1').first().textContent(), 'A journey through light, color, and motion');
            assert.equal(await page.locator('.dearrow-tooltip').count(), 0);
            if (options.fixture === 'watch-dark' || options.javascript === false) assert.ok(!requests.some(url => url.startsWith('/api/v1/dearrow/')));
            assert.deepEqual(errors, []);
            await context.close();
        }
    });

    test(`${engine}: DeArrow preference controls submit without JavaScript`, async () => {
        const {page, context} = await pageFor(engine, {fixture: 'preferences', javascript: false});
        assert.equal(await page.locator('#dearrow_enabled').isChecked(), false);
        assert.equal(await page.locator('#dearrow_show_original').isChecked(), true);
        await page.locator('#dearrow_enabled').check();
        await page.locator('#dearrow_show_original').uncheck();
        const posted = page.waitForRequest(request => request.method() === 'POST');
        await page.getByRole('button', {name: 'Save preferences', exact: true}).click();
        const body = new URLSearchParams((await posted).postData());
        assert.equal(body.get('dearrow_enabled'), 'on');
        assert.equal(body.has('dearrow_show_original'), false);
        await context.close();
    });
}
