'use strict';
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { gzipSync } = require('node:zlib');
const playwright = require('playwright');
const root = path.resolve(__dirname, '../..');
const generated = process.env.FRONTEND_FIXTURES || path.join(__dirname, '.generated');
const artifacts = path.join(__dirname, 'artifacts');
const engines = (process.env.FRONTEND_BROWSERS || 'chromium,firefox').split(',');
const browsers = {};
fs.mkdirSync(artifacts, { recursive: true });
const queue = JSON.parse(fs.readFileSync(path.join(generated, 'queue.json')));

before(async () => {
    for (const engine of engines) browsers[engine] = await playwright[engine].launch({ headless: true });
});
after(async () => { for (const browser of Object.values(browsers)) await browser.close(); });

// Only playback and upstream responses are stubbed. Templates, CSS and UI scripts
// are production code. No request is allowed to escape this fixture origin.
const playerStub = `
window.__ended = []; window.__time = 0;
window.player = {
 on: function(event, cb) { if (event === 'ended') window.__ended.push(cb); },
 off: function(event, cb) { if (event === 'ended') window.__ended = window.__ended.filter(f => f !== cb); },
 currentTime: function(value) { if (value !== undefined) window.__time = value; return window.__time; }
};`;
const picture = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"><defs><linearGradient id="sky" x2="1" y2="1"><stop stop-color="#213b6b"/><stop offset=".6" stop-color="#744287"/><stop offset="1" stop-color="#df9378"/></linearGradient></defs><path fill="url(#sky)" d="M0 0h1280v720H0z"/><circle cx="860" cy="230" r="92" fill="#f4ccaf"/><path d="m0 520 360-330 440 440 250-285 230 235v140H0z" fill="#1e253d"/><path d="m0 655 430-215 470 200 380-160v240H0z" fill="#131b2d"/></svg>`;

async function pageFor(engine, options = {}) {
    const context = await browsers[engine].newContext({
        viewport: { width: options.width || 1440, height: options.height || 1000 },
        javaScriptEnabled: options.javascript !== false,
        colorScheme: options.systemTheme || 'dark',
        reducedMotion: 'reduce',
        hasTouch: Boolean(options.touch)
    });
    const page = await context.newPage();
    const errors = [];
    const requests = [];
    page.on('pageerror', error => errors.push(error.message));
    let queueCalls = 0;
    let transcriptCalls = 0;
    const fixture = options.fixture || 'watch-dark';
    await page.route('**/*', async route => {
        const url = new URL(route.request().url());
        requests.push(url.pathname + url.search);
        if (route.request().isNavigationRequest()) {
            return route.fulfill({ contentType: 'text/html', body: fs.readFileSync(path.join(generated, fixture + '.html'), 'utf8') });
        }
        if (url.pathname === '/api/v1/auth/subscriptions') return route.fulfill({ contentType: 'application/json', body: '[]' });
        if (url.pathname === '/api/v1/auth/notifications') return route.fulfill({ contentType: 'text/event-stream', body: ': fixture\n\n' });
        if (/^\/api\/v1\/(playlists|mixes)\//.test(url.pathname)) {
            queueCalls++;
            if (options.queueError && queueCalls <= options.queueError) return route.fulfill({ status: 500, body: '{}' });
            const response = options.queue || (fixture === 'watch-thin' ? JSON.parse(fs.readFileSync(path.join(generated, 'queue-thin.json'))) : queue);
            return route.fulfill({ contentType: 'application/json', body: JSON.stringify(response) });
        }
        if (url.pathname.startsWith('/api/v1/transcripts/')) {
            transcriptCalls++;
            if (options.transcriptError && transcriptCalls <= options.transcriptError) return route.fulfill({ status: 500, body: '{}' });
            return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ transcript: { autoGenerated: url.searchParams.get('label').includes('Indonesian'), body: [
                { type: 'heading', startMs: 0, line: 'Introduction' },
                { type: 'regular', startMs: 80000, line: 'Finding the light <img src=x onerror=alert(1)>' },
                { type: 'regular', startMs: 225000, line: 'Color in motion' }
            ] } }) });
        }
        if (url.pathname === '/js/silvermine-videojs-quality-selector.min.js' && !options.realPlayer) return route.fulfill({ contentType: 'application/javascript', body: '' });
        if (url.pathname === '/js/player.js' && !options.realPlayer) return route.fulfill({ contentType: 'application/javascript', body: playerStub });
        if (url.pathname.startsWith('/videojs/') && !options.realPlayer) return route.fulfill({ contentType: url.pathname.endsWith('.css') ? 'text/css' : 'application/javascript', body: '' });
        if (url.pathname.startsWith('/vi/') || url.pathname.startsWith('/ggpht')) return route.fulfill({ contentType: 'image/svg+xml', body: picture });
        if (options.realPlayer && url.pathname === '/latest_version') {
            const body = fs.readFileSync(path.join(generated, 'fixture.webm'));
            const range = route.request().headers().range;
            const match = range && range.match(/bytes=(\d+)-(\d*)/);
            if (match) {
                const start = Number(match[1]);
                const end = match[2] ? Math.min(Number(match[2]), body.length - 1) : body.length - 1;
                return route.fulfill({ status: 206, contentType: 'video/webm', headers: { 'accept-ranges': 'bytes', 'content-range': `bytes ${start}-${end}/${body.length}` }, body: body.subarray(start, end + 1) });
            }
            return route.fulfill({ contentType: 'video/webm', headers: { 'accept-ranges': 'bytes' }, body });
        }
        if (url.pathname.startsWith('/api/v1/captions/')) return route.fulfill({ contentType: 'text/vtt', body: 'WEBVTT\n\n00:00.000 --> 00:04.000\nFixture captions\n' });
        if (url.pathname === '/themes/fixture-theme/theme.css') return route.fulfill({ contentType: 'text/css', body: 'body { --fixture-theme: active; }' });
        if (/^\/(css|js|fonts|videojs|themes)\//.test(url.pathname)) {
            const file = path.join(root, 'assets', url.pathname);
            if (!fs.existsSync(file)) return route.fulfill({ status: 404, body: '' });
            return route.fulfill({ contentType: url.pathname.endsWith('.css') ? 'text/css' : url.pathname.endsWith('.js') ? 'application/javascript' : url.pathname.endsWith('.svg') ? 'image/svg+xml' : 'application/octet-stream', body: fs.readFileSync(file) });
        }
        return route.fulfill({ contentType: 'application/json', body: '{}' });
    });
    await page.goto('https://invidious.test/' + (fixture.startsWith('watch') ? 'watch?v=2isYuQZMbdU&list=PLfixture&index=2' : fixture.startsWith('preferences') ? 'preferences' : 'feed/popular'));
    return { page, context, errors, requests, queueCalls: () => queueCalls, transcriptCalls: () => transcriptCalls };
}

for (const engine of engines) {
    test(`${engine}: theme cards render and submit without JavaScript`, async () => {
        const { page, context } = await pageFor(engine, { fixture: 'preferences', javascript: false, width: 390 });
        const radio = page.getByRole('radio', { name: 'Modern Neon' });
        assert.equal(await radio.isChecked(), true);
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'modern-neon');
        assert.equal(await page.locator('.theme-card-selected').isVisible(), true);
        await radio.scrollIntoViewIfNeeded();
        const preview = page.locator('.theme-card img');
        await preview.waitFor();
        assert.equal(await preview.evaluate(img => img.complete && img.naturalWidth > 0), true);
        await radio.focus();
        await page.keyboard.press('Space');
        await page.locator('.theme-picker').screenshot({ path: path.join(artifacts, `${engine}-theme-picker.png`) });
        const posted = page.waitForRequest(request => request.method() === 'POST');
        await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
        assert.equal(new URLSearchParams((await posted).postData()).get('theme'), 'modern-neon');
        await context.close();
    });
    test(`${engine}: alternative theme loads in isolation and supports keyboard selection`, async () => {
        const { page, context, requests } = await pageFor(engine, { fixture: 'preferences-alternative' });
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'fixture-theme');
        assert.equal(await page.getByRole('radio', { name: 'Fixture Theme' }).isChecked(), true);
        assert.ok(requests.some(url => url.startsWith('/themes/fixture-theme/theme.css')));
        assert.ok(!requests.some(url => url.startsWith('/themes/modern-neon/theme.css')));
        await page.getByRole('radio', { name: 'Fixture Theme' }).focus();
        await page.keyboard.press('ArrowLeft');
        assert.equal(await page.getByRole('radio', { name: 'Modern Neon' }).isChecked(), true);
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'fixture-theme');
        await page.locator('#toggle_theme').click();
        assert.equal(await page.locator('body').getAttribute('data-theme'), 'fixture-theme');
        await context.close();
    });
    test(`${engine}: actual Video.js player retains playback, seeking and controls`, async () => {
        for (const [width, height, touch] of [[1440, 1000, false], [320, 700, true], [390, 844, true], [768, 1000, true], [844, 390, true], [1024, 768, false]]) {
            const { page, context, errors } = await pageFor(engine, { realPlayer: true, touch, width, height });
            await page.waitForFunction(() => window.player && typeof player.play === 'function');
            await page.evaluate(() => { player.muted(true); player.play(); });
            await page.waitForFunction(() => player.currentTime() > 0.1, { timeout: 10000 });
            await page.evaluate(() => { player.pause(); player.currentTime(1); player.playbackRate(1.5); });
            assert.equal(await page.evaluate(() => player.paused()), true);
            assert.equal(await page.evaluate(() => player.playbackRate()), 1.5);
            await page.waitForFunction(() => player.currentTime() >= 0.9);
            assert.ok(await page.evaluate(() => player.currentTime() >= 0.9));
            assert.equal(await page.locator('.vjs-fullscreen-control').count(), 1);
            assert.equal(await page.locator('button.vjs-captions-button').count(), 1);
            assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
            const playerBox = await page.locator('#player').boundingBox();
            const fullBox = await page.locator('.vjs-fullscreen-control').boundingBox();
            assert.ok(fullBox.width >= 44 && fullBox.height >= 44);
            assert.ok(fullBox.x >= playerBox.x && fullBox.x + fullBox.width <= playerBox.x + playerBox.width + 1);
            assert.equal(await page.locator('.vjs-wide-control').isVisible(), width >= 1100);
            await page.screenshot({ path: path.join(artifacts, `${engine}-actual-player-${width}.png`) });
            if ([390, 1440].includes(width)) await page.screenshot({ path: path.join(artifacts, `${engine}-actual-player-${touch ? 'mobile' : 'desktop'}.png`) });
            assert.deepEqual(errors, []);
            await context.close();
        }
    });

    test(`${engine}: header is horizontal and Library navigation is always available`, async () => {
        const { page, context, errors } = await pageFor(engine, { fixture: 'browse-dark' });
        const rail = page.locator('.navigation-rail');
        for (const feed of ['history', 'subscriptions', 'playlists']) assert.equal(await rail.locator(`a[href="/feed/${feed}"]`).isVisible(), true);
        assert.equal(await rail.locator('a[href="/preferences"]').isVisible(), true);
        assert.equal(await rail.locator('a[href="/"]').count(), 0);
        assert.equal(await page.locator('.index-link').getAttribute('href'), '/');
        assert.equal((await page.locator('.navigation-menu > summary').textContent()).trim(), '☰');
        assert.equal(await page.locator('.user-field a[href*="preferences"]').count(), 0);
        assert.ok((await page.locator('.index-link').boundingBox()).height <= 40);
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator('.navigation-menu > summary').click();
        for (const feed of ['history', 'subscriptions', 'playlists']) assert.equal(await page.locator(`.navigation-menu a[href="/feed/${feed}"]`).isVisible(), true);
        await page.keyboard.press('Escape');
        assert.equal(await page.locator('.navigation-menu').getAttribute('open'), null);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: player wide control, paused idle state and keyboard access`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true });
        await page.evaluate(() => { player.muted(true); player.play(); });
        await page.waitForFunction(() => player.currentTime() > 0.1);
        await page.evaluate(() => player.pause());
        const wide = page.locator('.vjs-wide-control');
        assert.equal(await wide.getAttribute('title'), 'Wide player');
        assert.equal(await page.locator('.watch-actions #wide-player').count(), 0);
        const before = await page.locator('#player-container').boundingBox();
        assert.equal(await wide.getAttribute('aria-pressed'), 'true');
        await wide.click();
        assert.equal(await wide.getAttribute('aria-pressed'), 'false');
        assert.ok((await page.locator('#player-container').boundingBox()).width < before.width);
        await wide.click();
        assert.equal(await wide.getAttribute('aria-pressed'), 'true');
        const wideBox = await wide.boundingBox();
        const fullBox = await page.locator('.vjs-fullscreen-control').boundingBox();
        assert.ok(Math.abs(fullBox.x - (wideBox.x + wideBox.width)) <= 4);
        assert.ok(wideBox.width >= 44 && wideBox.height >= 44);
        await page.mouse.move(0, 0);
        await page.waitForFunction(() => !player.userActive(), null, { timeout: 6000 });
        await page.waitForFunction(() => getComputedStyle(player.controlBar.el()).opacity === '0');
        assert.equal(await page.evaluate(() => player.paused()), true);
        await page.mouse.move(before.x + 100, before.y + 100, { steps: 5 });
        await page.waitForFunction(() => getComputedStyle(player.controlBar.el()).opacity === '1');
        // Keyboard focus must keep the focused control accessible during inactivity.
        await page.keyboard.press('Tab');
        await wide.focus();
        await page.evaluate(() => player.userActive(false));
        assert.equal(await wide.isVisible(), true);
        await page.keyboard.press('Enter');
        assert.equal(await wide.getAttribute('aria-pressed'), 'false');
        assert.equal(await page.evaluate(() => player.paused()), true);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: cached history titles and compact desktop playlist library`, async () => {
        const history = await pageFor(engine, { fixture: 'history' });
        const cards = history.page.locator('.media-card');
        assert.match(await cards.nth(0).textContent(), /A journey through light/);
        assert.match(await cards.nth(1).textContent(), /Light <study> & color/);
        assert.equal(await cards.nth(2).locator('p').count(), 0);
        assert.equal(await cards.nth(2).locator('img').count(), 1);
        assert.equal(history.requests.some(url => url.startsWith('/api/v1/videos/')), false);
        assert.deepEqual(history.errors, []);
        await history.context.close();
        const library = await pageFor(engine, { fixture: 'playlist-library' });
        const image = library.page.locator('.playlist-library img').first();
        assert.ok((await image.boundingBox()).width < 420);
        await library.page.setViewportSize({ width: 390, height: 844 });
        assert.ok((await image.boundingBox()).width > 300);
        assert.deepEqual(library.errors, []);
        await library.context.close();
    });

    test(`${engine}: mobile paused controls hide, wake on tap, and keep menus usable`, async () => {
        const { page, context, errors } = await pageFor(engine, { realPlayer: true, touch: true, width: 390, height: 844 });
        await page.evaluate(() => { player.muted(true); player.play(); });
        await page.waitForFunction(() => player.currentTime() > 0.1);
        await page.evaluate(() => player.pause());
        await page.waitForFunction(() => !player.userActive(), null, { timeout: 6000 });
        await page.locator('.mobile-operations-bar').waitFor({ state: 'hidden' });
        const box = await page.locator('#player').boundingBox();
        await page.touchscreen.tap(box.x + box.width / 2, box.y + box.height / 2);
        await page.waitForFunction(() => player.userActive());
        await page.locator('.mobile-operations-bar').waitFor({ state: 'visible' });
        assert.equal(await page.locator('.mobile-operations-bar').isVisible(), true);
        assert.equal(await page.evaluate(() => player.paused()), true);
        await page.locator('button.vjs-playback-rate').tap();
        const menu = page.locator('.vjs-playback-rate .vjs-menu');
        await menu.locator('.vjs-menu-content').waitFor({ state: 'visible', timeout: 3000 });
        await page.evaluate(() => player.userActive(false));
        assert.equal(await menu.locator('.vjs-menu-content').isVisible(), true);
        const menuBox = await menu.locator('.vjs-menu-content').boundingBox();
        assert.ok(menuBox.x >= box.x && menuBox.x + menuBox.width <= box.x + box.width + 1);
        assert.ok(menuBox.y + menuBox.height <= box.y + box.height + 1);
        await page.screenshot({ path: path.join(artifacts, `${engine}-player-mobile-menu.png`) });
        await menu.getByText('1.5x', { exact: true }).tap();
        await page.waitForFunction(() => player.playbackRate() === 1.5, null, { timeout: 3000 });
        await menu.locator('.vjs-menu-content').waitFor({ state: 'hidden' });
        assert.equal(await page.evaluate(() => player.playbackRate()), 1.5);
        assert.equal(await page.evaluate(() => player.paused()), true);
        await page.setViewportSize({ width: 320, height: 700 });
        await page.locator('button.vjs-playback-rate').tap();
        await menu.locator('.vjs-menu-content').waitFor({ state: 'visible' });
        const smallPlayer = await page.locator('#player').boundingBox();
        const smallMenu = await menu.locator('.vjs-menu-content').boundingBox();
        assert.ok(smallMenu.y + smallMenu.height <= smallPlayer.y + smallPlayer.height + 1);
        await menu.getByText('1.5x', { exact: true }).tap();
        await menu.locator('.vjs-menu-content').waitFor({ state: 'hidden' });
        assert.equal(await page.evaluate(() => player.playbackRate()), 1.5);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: queue selects a repeated occurrence, and keeps recommendations separate`, async () => {
        const { page, context, errors } = await pageFor(engine);
        await page.waitForSelector('.queue-row a[aria-current]');
        assert.equal(await page.locator('.queue-row:has([aria-current])').getAttribute('data-index'), '2');
        assert.equal(await page.locator('.queue-row [aria-current]').count(), 1);
        assert.match(await page.locator('[data-direction=previous]').getAttribute('href'), /index=1/);
        assert.match(await page.locator('[data-direction=next]').getAttribute('href'), /index=3/);
        assert.equal(await page.locator('#queue-title').textContent(), 'Light & motion <study>');
        assert.equal(await page.locator('.recommendations a[href*="list="]').count(), 0);
        assert.equal(await page.evaluate(() => window.__ended.length), 1);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: queue failure is retryable and does not enable recommendation autoplay`, async () => {
        const { page, context, errors } = await pageFor(engine, { queueError: 1 });
        await page.waitForSelector('#queue-retry:not([hidden])');
        assert.equal(await page.evaluate(() => window.__ended.length), 0);
        await page.locator('#queue-retry').click();
        await page.waitForSelector('.queue-row [aria-current]');
        assert.equal(await page.evaluate(() => window.__ended.length), 1);
        await page.evaluate(() => get_playlist('PLfixture'));
        await page.waitForSelector('.queue-row [aria-current]');
        assert.equal(await page.evaluate(() => window.__ended.length), 1);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: missing, empty and ended queues do not attach an advancement handler`, async () => {
        for (const response of [{ playlistHtml: '<ol></ol>', nextVideo: null }, { ...queue, nextVideo: null }]) {
            const { page, context, errors } = await pageFor(engine, { queue: response });
            await page.waitForFunction(() => document.getElementById('playlist').getAttribute('aria-busy') === 'false');
            assert.equal(await page.evaluate(() => window.__ended.length), 0);
            assert.equal(await page.locator('[data-direction=next]').count(), 0);
            assert.ok(await page.locator('#queue-status').textContent());
            assert.deepEqual(errors, []);
            await context.close();
        }
    });

    test(`${engine}: transcript loads on demand, searches safely, seeks, caches, and retries`, async () => {
        const { page, context, errors, requests, transcriptCalls } = await pageFor(engine, { transcriptError: 1 });
        assert.equal(transcriptCalls(), 0);
        assert.equal(requests.some(url => url.startsWith('/js/transcript.js')), false);
        await page.locator('#transcript-panel > summary').click();
        await page.waitForSelector('#transcript-retry:not([hidden])');
        await page.locator('#transcript-retry').click();
        await page.waitForSelector('.transcript-line');
        assert.equal(await page.locator('.transcript-line img').count(), 0);
        await page.locator('#transcript-search').fill('Finding');
        assert.equal(await page.locator('.transcript-line').count(), 1);
        await page.locator('.transcript-line button').click();
        assert.equal(await page.evaluate(() => window.__time), 80);
        await page.locator('#transcript-search').fill('not present');
        assert.equal(await page.locator('#transcript-status').textContent(), 'No matching transcript lines.');
        await page.locator('#transcript-search').fill('');
        await page.locator('#transcript-language').selectOption({ index: 1 });
        await page.waitForFunction(() => document.getElementById('transcript-status').textContent.includes('Automatically'));
        await page.locator('#transcript-language').selectOption({ index: 0 });
        assert.equal(transcriptCalls(), 3);
        await page.locator('#timestamp-list a').nth(1).click();
        assert.equal(await page.evaluate(() => window.__time), 80);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: mobile queue is immediately below player, collapsible, and keyboard operable`, async () => {
        const { page, context, errors } = await pageFor(engine, { width: 390 });
        await page.waitForSelector('.queue-row', { state: 'attached' });
        assert.equal(await page.locator('#playlist').isVisible(), false);
        const player = await page.locator('#player-container').boundingBox();
        const panel = await page.locator('#playlist-panel').boundingBox();
        const title = await page.locator('.watch-heading').boundingBox();
        assert.ok(player.y + player.height <= panel.y + 1);
        assert.ok(panel.y + panel.height <= title.y + 1);
        await page.locator('#queue-toggle').focus();
        await page.keyboard.press('Enter');
        assert.equal(await page.locator('#playlist').isVisible(), true);
        assert.equal(await page.locator('#queue-toggle').getAttribute('aria-expanded'), 'true');
        assert.equal(await page.evaluate(() => document.activeElement.id), 'queue-toggle');
        await page.evaluate(() => {
            const list = document.getElementById('playlist');
            const rows = list.querySelector('ol');
            for (let i = 0; i < 8; i++) rows.appendChild(rows.lastElementChild.cloneNode(true));
            list.scrollTop = list.scrollHeight;
        });
        const scroll = await page.locator('#playlist').evaluate(el => el.scrollTop);
        assert.ok(scroll > 0);
        await page.setViewportSize({ width: 390, height: 800 });
        await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
        assert.equal(await page.locator('#playlist').evaluate(el => el.scrollTop), scroll);
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: theme switching preserves density and page layout`, async () => {
        const { page, context, errors } = await pageFor(engine, { fixture: 'browse-compact' });
        await page.locator('#toggle_theme').click();
        assert.equal(await page.locator('body').getAttribute('data-density'), 'compact');
        assert.equal(await page.locator('body').getAttribute('class'), 'light-theme');
        assert.deepEqual(errors, []);
        await context.close();
    });

    test(`${engine}: no-JavaScript and thin modes retain essential navigation`, async () => {
        const nojs = await pageFor(engine, { javascript: false });
        assert.equal(await nojs.page.locator('#queue-title').isVisible(), true);
        assert.equal(await nojs.page.locator('#share-video').isVisible(), false);
        assert.equal(await nojs.page.locator('#transcript-panel').isVisible(), false);
        if (await nojs.page.locator('#description-box').getAttribute('open') === null) await nojs.page.locator('#description-box > summary').click();
        assert.equal(await nojs.page.locator('#descriptionWrapper').isVisible(), true);
        await nojs.context.close();
        const thin = await pageFor(engine, { fixture: 'watch-thin' });
        await thin.page.waitForSelector('.queue-row');
        assert.equal(await thin.page.locator('.queue-row img, .recommendation img').count(), 0);
        assert.deepEqual(thin.errors, []);
        await thin.context.close();
    });

    test(`${engine}: responsive layouts and representative visual snapshots`, async () => {
        for (const fixture of ['watch-dark', 'watch-light', 'watch-rtl', 'browse-dark', 'browse-light', 'browse-compact', 'browse-signed-in', 'preferences', 'history', 'playlist-library']) {
            const session = await pageFor(engine, { fixture });
            for (const width of [320, 390, 768, 1024, 1440, 1920]) {
                await session.page.setViewportSize({ width, height: 1000 });
                await session.page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
                assert.ok(await session.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${fixture} overflows at ${width}px`);
                if ([390, 1440].includes(width)) await session.page.screenshot({ path: path.join(artifacts, `${engine}-${fixture}-${width}.png`), fullPage: true });
            }
            assert.deepEqual(session.errors, [], fixture);
            await session.context.close();
        }
    });

    test(`${engine}: enlarged text and phone landscape keep navigation usable`, async () => {
        for (const fixture of ['watch-dark', 'browse-signed-in', 'preferences']) {
            const { page, context, errors } = await pageFor(engine, { fixture, width: 390 });
            await page.evaluate(() => document.documentElement.style.fontSize = '200%');
            await page.evaluate(() => document.fonts.ready);
            await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
            const overflow = await page.evaluate(() => Array.from(document.querySelectorAll('body *')).filter(el => {
                const box = el.getBoundingClientRect();
                return box.width && box.right > innerWidth + 1;
            }).slice(0, 8).map(el => `${el.tagName}.${el.className}#${el.id}`));
            assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${fixture}: enlarged text ${overflow.join(', ')}`);
            await page.evaluate(() => document.documentElement.style.fontSize = '');
            await page.setViewportSize({ width: 844, height: 390 });
            await page.locator('.navigation-menu > summary').click();
            assert.equal(await page.locator('.navigation-menu a[href="/feed/subscriptions"]').isVisible(), true);
            assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${fixture}: landscape`);
            assert.deepEqual(errors, []);
            await context.close();
        }
    });
}

test('library navigation survives custom feed settings without channel management links', () => {
    const html = fs.readFileSync(path.join(generated, 'navigation-subscribed.html'), 'utf8');
    for (const feed of ['history', 'subscriptions', 'playlists']) assert.ok(html.includes(`href="/feed/${feed}"`));
    assert.ok(html.includes('href="/feed/subscriptions" aria-current=page'));
    assert.ok(!html.includes('/subscription_manager'));
    assert.ok(!html.includes('/channel/'));
    assert.ok(!html.includes('<img'));
});

test('UI asset additions stay below the 30KB compressed initial-load budget', () => {
    const baseline = require('./asset-baseline.json');
    let delta = 0;
    for (const [file, originalBytes] of Object.entries(baseline.gzipBytes)) {
        const current = fs.readFileSync(path.join(root, 'assets', file));
        delta += gzipSync(current).length - originalBytes;
    }
    assert.ok(delta <= 30 * 1024, `${delta} bytes added`);
    console.log(`Initial UI asset increase: ${delta} gzip bytes; transcript loaded on demand.`);
});
